run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - govet
    - ineffassign
    - typecheck
    - revive
    - gofmt
    - goimports
    - misspell
    - errname
    - whitespace
    - goconst
    - gocritic
    - bodyclose
    - nilnil
    - noctx
    - exportloopref
    - prealloc
    - unconvert
    - unparam

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
      - name: blank-imports
      - name: context-as-first-argument
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/mac/go-pixo
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gocritic
        - revive
